"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""
from io import BytesIO
import struct

class robot_control_cmd_lcmt(object):
    __slots__ = ["mode", "gait_id", "contact", "life_count", "vel_des", "rpy_des", "pos_des", "acc_des", "ctrl_point", "foot_pose", "step_height", "value", "duration"]

    __typenames__ = ["int8_t", "int8_t", "int8_t", "int8_t", "float", "float", "float", "float", "float", "float", "float", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, [3], [3], [3], [6], [3], [6], [2], None, None]

    def __init__(self):
        self.mode = 0
        self.gait_id = 0
        self.contact = 0
        self.life_count = 0
        self.vel_des = [ 0.0 for dim0 in range(3) ]
        self.rpy_des = [ 0.0 for dim0 in range(3) ]
        self.pos_des = [ 0.0 for dim0 in range(3) ]
        self.acc_des = [ 0.0 for dim0 in range(6) ]
        self.ctrl_point = [ 0.0 for dim0 in range(3) ]
        self.foot_pose = [ 0.0 for dim0 in range(6) ]
        self.step_height = [ 0.0 for dim0 in range(2) ]
        self.value = 0
        self.duration = 0

    # 将类的实例编码为字节流
    def encode(self):
        buf = BytesIO()
        buf.write(robot_control_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()   #将buf中存储的字节流作为函数的返回值

    # 编码方法的辅助函数，将类的实例编码为字节流
    def _encode_one(self, buf):
        # b是byte i是int  f是float
        # 将打包的字节写入到buf对象中
        buf.write(struct.pack(">bbbb", self.mode, self.gait_id, self.contact, self.life_count))
        buf.write(struct.pack('>3f', *self.vel_des[:3]))
        buf.write(struct.pack('>3f', *self.rpy_des[:3]))
        buf.write(struct.pack('>3f', *self.pos_des[:3]))
        buf.write(struct.pack('>6f', *self.acc_des[:6]))
        buf.write(struct.pack('>3f', *self.ctrl_point[:3]))
        buf.write(struct.pack('>6f', *self.foot_pose[:6]))
        buf.write(struct.pack('>2f', *self.step_height[:2]))
        buf.write(struct.pack(">ii", self.value, self.duration))

    # 将字节流解码为类的实例
    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):   # 变量data是否有read属性
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_control_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_control_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_control_cmd_lcmt()
        self.mode, self.gait_id, self.contact, self.life_count = struct.unpack(">bbbb", buf.read(4))
        self.vel_des = struct.unpack('>3f', buf.read(12))
        self.rpy_des = struct.unpack('>3f', buf.read(12))
        self.pos_des = struct.unpack('>3f', buf.read(12))
        self.acc_des = struct.unpack('>6f', buf.read(24))
        self.ctrl_point = struct.unpack('>3f', buf.read(12))
        self.foot_pose = struct.unpack('>6f', buf.read(24))
        self.step_height = struct.unpack('>2f', buf.read(8))
        self.value, self.duration = struct.unpack(">ii", buf.read(8))
        return self

    @staticmethod
    # 递归计算结构体的hash值
    def _get_hash_recursive(parents):
        if robot_control_cmd_lcmt in parents:
            return 0
        tmphash = (0x476b61e296af96f5) & 0xffffffffffffffff
        tmphash = (((tmphash << 1) & 0xffffffffffffffff) + (tmphash >> 63)) & 0xffffffffffffffff
        return tmphash

    @staticmethod
    def _get_packed_fingerprint():
        if robot_control_cmd_lcmt._packed_fingerprint is None:
            robot_control_cmd_lcmt._packed_fingerprint = struct.pack(">Q", robot_control_cmd_lcmt._get_hash_recursive([]))
            # 上面是将计算结构体的哈希值并将hash值打包成一个无符号长整形数存储在_packed_fingerprint中
        return robot_control_cmd_lcmt._packed_fingerprint

    _packed_fingerprint = None

    # 获得消息的hash值方法
    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_control_cmd_lcmt._get_packed_fingerprint())[0]